/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT tone.cdb */

/*  Include Header Files  */
#include <std.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>

#ifdef __cplusplus
extern "C" {
#endif

extern SWI_Obj KNL_swi;
extern TSK_Obj TSK_idle;
extern TSK_Obj userTask;
extern LOG_Obj LOG_system;


#ifdef __cplusplus
}
#endif /* extern "C" */
